<?php if( $block->dataValue( 'body' ) ) { ?>
	<div class="et-annot" data-highlight="<?= $block->dataValue( 'highlight' ); ?>" data-type="<?= $block->dataValue( 'type' ); ?>">
		<div class="et-annot-inner">
			<div class="et-annot-toolbar">
				<!-- <div class="et-annot-type"><?#= $block->dataValue( 'type' ); ?></div> -->
				<div class="et-annot-index"></div>
				<div class="et-gap"></div>
				<button class="et-annot-toggle" name="Toggle annotation size">
					<div>&plus;</div>
					<div>&minus;</div>
				</button>
				<button class="et-annot-close" name="Close annot">
					<div>&times;</div>
				</button>
			</div>


			<?php if( isset( $reference['image'] ) ) { ?>
					<div class="et-annot-images">
						<?= $reference['image'] ?>
					</div>
			<?php } ?>

			<div class="et-annot-row et-annot-body">
				<?= $block->dataValue( 'body' ); ?>
			</div>

			<?php if( $block->dataValue( 'citation' ) ) { ?>
				<div class="et-annot-row et-annot-ref">
					<?= $block->dataValue( 'citation' ) ?>
				</div>
			<?php } ?>

			<?php if( $reference && isset( $reference['title'] ) ) { ?>
				<div class="et-annot-row et-annot-ref">
					Read more: <?= $reference['title'] ?>
				</div>
			<?php } ?>

		</div>
	</div>
<?php } ?>