	</div>
</div>
<div class="col col-12">
	<div class="exploratory-text-block row">
		<div class="col col-12 col-sm-4">
			<div class="et-side et-side-empty">
				<div class="et-side-inner">
					<div class="et-side-key">
						<ul>
							<li class="entity"><strong>Person</strong><!-- : Biographical information for people</li> -->
							<li class="context"><strong>Context</strong><!-- : Historical context for events or arguments</li> -->
							<li class="primary"><strong>Primary source</strong><!-- : Commentary on thematic connections to other documents from the collection</li> -->
						</ul>
					</div>
					<div class="et-side-empty-note">
						<em>Nothing selected. Click on the highlighted text to view annotations.</em>
					</div>
				</div>
			</div>
		</div>

		<div class="col col-12 col-sm-8">
			<div class="et-inner row">

				<?php if( isset( $reference['title'] ) ) { ?>
					<div class="et-body-header">
						<h2><?= $reference['title'] ?></h2>
					</div>
				<?php } ?>
				
				<div class="et-body">
					<?= $block->dataValue( 'body' ); ?>
				</div>

				<div class="et-item-ref row">
					<div class="col col-12 col-sm-4">
						<?php if( isset( $reference['url'] ) ) { ?>
							<a href="<?= $reference['url'] ?>" target="_blank">
								<?= $reference['image']; ?>
							</a>
						<?php } ?>
					</div>
					<div class="col col-12 col-sm-8">
						<?php if( isset( $reference['title'] ) ) { ?>
							<div class="et-item-ref-link">
								View scanned document:
								<a href="<?= $reference['url'] ?>" target="_blank"><?= $reference['title'] ?></a>
							</div>
							<div class="et-item-ref-cite">
								<cite><?= $reference['citation'] ?></cite>
							</div>
						<?php } ?>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>
<div class="col col-4"></div>
<div class="col col-8">
	<div class="column">
