	</div>
</div>
<div class="col col-12">
	<div class="exploratory-text-block row">
		<div class="col col-12 col-sm-4">
			<div class="et-side">
				<div class="et-side-inner">

				</div>
			</div>
		</div>

		<div class="col col-12 col-sm-8">
			<div class="et-inner row">

				<?= $block->dataValue( 'body' ); ?>

			</div>
		</div>

	</div>
</div>
<div class="col col-4"></div>
<div class="col col-8">
	<div class="column">
